
INSERT INTO `khach_hang` (`id`, `ma_khach_hang`, `ho_ten`, `sdt`, `dia_chi`, `email`, `mst`, `phan_loai`, `so_du_ky_truoc`,
 `ma_dai_ly`, `ngay_tao`, `ngay_nhac`, `phi_vn`, `phi_vj`, `phi_jets`, `phi_bb`, `ghi_chu`) VALUES
(147, '2', '2', NULL, NULL, NULL, NULL, '2', '11500000.0000', NULL, '2018-12-08', NULL, NULL, NULL, NULL, NULL, NULL),
(148, '0.2 TTKTĐB', 'TTKTĐB', NULL, NULL, NULL, NULL, 'công ty', '0.0000', NULL, '2018-12-09', NULL, NULL, NULL, NULL, NULL, NULL),
(150, 'tessst', 'tesssst', NULL, NULL, NULL, NULL, 'Khách lẻ', '0.0000', NULL, '2018-12-27', NULL, NULL, NULL, NULL, NULL, NULL);

--
-- Dumping data for table `tbphihanhly`
--

INSERT INTO `phi_hanh_ly` (`id`, `hanh_ly`, `phi`, `ghi_chu`, `hang_bay`) VALUES
(1, '5kg', '50000.0000', NULL, NULL),
(2, '10kg', '80000.0000', NULL, NULL),
(3, '15kg', '100000.0000', NULL, NULL);

--
-- Dumping data for table `tbsanbay`
--

INSERT INTO `san_bay` (`ma_san_bay`, `ten_san_bay`, `phan_loai`, `loai_a`) VALUES
('AMS', 'Amsterdam  (AMS)', 'Châu Âu', NULL),
('ATL', 'Atlanta Hartsfield  (ATL)', 'Hoa Kỳ', NULL),
('AUS', 'Austin  (AUS)', 'Hoa Kỳ', NULL),
('BCN', 'Barcelona, Spain  (BCN)', 'Châu Âu', NULL),
('BJS', 'Beijing  (BJS)', 'Đông Bắc Á', NULL),
('BKK', 'Bangkok  (BKK)', 'Đông Nam Á', NULL),
('BMV', 'Ban Me Thuot  (BMV)', 'Việt Nam', 1),
('BOS', 'Boston, Logan  (BOS)', 'Hoa Kỳ', NULL),
('CAH', 'Ca Mau  (CAH)', 'Việt Nam', NULL),
('CAN', 'Guangzhou  (CAN)', 'Đông Bắc Á', NULL),
('CGK', 'Jakarta  (CGK)', 'Đông Nam Á', NULL),
('CGO', 'Zhengzhou, China  (CGO)', 'Đông Bắc Á', NULL),
('CHI', 'Chicago, IL  (CHI)', 'Hoa Kỳ', NULL),
('CPH', 'Copenhagen, Denmark  (CPH)', 'Châu Âu', NULL),
('CTU', 'Chengdu  (CTU)', 'Đông Bắc Á', NULL),
('CXR', 'Nha Trang  (CXR)', 'Việt Nam', 1),
('CZX', 'Changzhou, China  (CZX)', 'Đông Bắc Á', NULL),
('DAD', 'Da Nang  (DAD)', 'Việt Nam', 1),
('DEN', 'Denver  (DEN)', 'Hoa Kỳ', NULL),
('DFW', 'Dallas/Fort Worth  (DFW)', 'Hoa Kỳ', NULL),
('DIN', 'Dien Bien  (DIN)', 'Việt Nam', NULL),
('DLI', 'Da Lat  (DLI)', 'Việt Nam', 1),
('ETZ', 'Lorraine TGV, France  (ETZ)', 'Châu Âu', NULL),
('FRA', 'Frankfurt  (FRA)', 'Châu Âu', NULL),
('FUK', 'Fukuoka  (FUK)', 'Đông Bắc Á', NULL),
('GVA', 'Geneva, Switzerland  (GVA)', 'Châu Âu', NULL),
('HAN', 'Ha Noi  (HAN)', 'Việt Nam', 1),
('HET', 'Hohhot, China  (HET)', 'Đông Bắc Á', NULL),
('HGH', 'Hangzhou, China  (HGH)', 'Đông Bắc Á', NULL),
('HKG', 'Hong Kong  (HKG)', 'Đông Bắc Á', NULL),
('HND', 'Haneda, Tokyo  (HND)', 'Đông Bắc Á', NULL),
('HNL', 'Honolulu  (HNL)', 'Hoa Kỳ', NULL),
('HOU', 'Houston  (HOU)', 'Hoa Kỳ', NULL),
('HPH', 'Hai Phong  (HPH)', 'Việt Nam', 1),
('HUI', 'Hue  (HUI)', 'Việt Nam', 1),
('ICN', 'Seoul  (ICN)', 'Đông Bắc Á', NULL),
('ITM', 'Osaka  (ITM)', 'Đông Bắc Á', NULL),
('JFK', 'New York, USA  (JFK)', 'Hoa Kỳ', NULL),
('KHH', 'Kaohsiung  (KHH)', 'Đông Bắc Á', NULL),
('KMG', 'Kunming, China  (KMG)', 'Đông Bắc Á', NULL),
('KUL', 'Kuala Lumpur  (KUL)', 'Đông Nam Á', NULL),
('LAX', 'Los Angeles  (LAX)', 'Hoa Kỳ', NULL),
('LON', 'London  (LON)', 'Châu Âu', NULL),
('LPQ', 'Luang Prabang  (LPQ)', 'Đông Dương', NULL),
('LYS', 'Lyon, France  (LYS)', 'Châu Âu', NULL),
('MEL', 'Melbourne  (MEL)', 'Châu Úc', NULL),
('MIA', 'Miami  (MIA)', 'Hoa Kỳ', NULL),
('MNL', 'Manila  (MNL)', 'Đông Nam Á', NULL),
('MRS', 'Marseille, France  (MRS)', 'Châu Âu', NULL),
('MSP', 'Minneapolis/St.Paul  (MSP)', 'Hoa Kỳ', NULL),
('NCE', 'Nice, France  (NCE)', 'Châu Âu', NULL),
('NGB', 'Ninhbo, China  (NGB)', 'Đông Bắc Á', NULL),
('NGO', 'Nagoya  (NGO)', 'Đông Bắc Á', NULL),
('NKG', 'Nanjing - Lokou, China  (NKG)', 'Đông Bắc Á', NULL),
('NNG', 'Nanning - Wuxu, China  (NNG)', 'Đông Bắc Á', NULL),
('NRT', 'Narita, Tokyo  (NRT)', 'Đông Bắc Á', NULL),
('OSA', 'Osaka  (OSA)', 'Đông Bắc Á', NULL),
('PAR', 'Paris  (PAR)', 'Châu Âu', NULL),
('PDX', 'Portland  (PDX)', 'Hoa Kỳ', NULL),
('PHL', 'Philadelphia  (PHL)', 'Hoa Kỳ', NULL),
('PNH', 'Phnom Penh  (PNH)', 'Đông Dương', NULL),
('PQC', 'Phu Quoc  (PQC)', 'Việt Nam', 1),
('PRG', 'Praque  (PRG)', 'Châu Âu', NULL),
('PUS', 'Busan  (PUS)', 'Đông Bắc Á', NULL),
('PXU', 'Pleiku  (PXU)', 'Việt Nam', NULL),
('QJZ', 'Nantes, France  (QJZ)', 'Châu Âu', NULL),
('QXB', 'Aix en Provence TGV, France  (QXB)', 'Châu Âu', NULL),
('QXG', 'Angers St-Laud, France  (QXG)', 'Châu Âu', NULL),
('QYG', 'Raiway, Germany  (QYG)', 'Châu Âu', NULL),
('REP', 'Siem Riep  (REP)', 'Đông Dương', NULL),
('RGN', 'Yangon  (RGN)', 'Đông Nam Á', NULL),
('RMQ', 'Đài Trung  (RMQ)', 'Đông Bắc Á', NULL),
('ROM', 'Rome  (ROM)', 'Châu Âu', NULL),
('SEA', 'Seattle, Tacoma  (SEA)', 'Hoa Kỳ', NULL),
('SFO', 'San Francisco  (SFO)', 'Hoa Kỳ', NULL),
('SGN', 'Ho Chi Minh City  (SGN)', 'Việt Nam', 1),
('SHA', 'Shanghai  (SHA)', 'Đông Bắc Á', NULL),
('SIN', 'Singapore  (SIN)', 'Đông Nam Á', NULL),
('STL', 'St Louis, Lambert  (STL)', 'Hoa Kỳ', NULL),
('SYD', 'Sydney  (SYD)', 'Châu Úc', NULL),
('TBB', 'Tuy Hoa  (TBB)', 'Việt Nam', NULL),
('THD', 'Thanh Hoa  (THD)', 'Việt Nam', NULL),
('TLS', 'Toulouse, France  (TLS)', 'Châu Âu', NULL),
('TPE', 'Taipei  (TPE)', 'Đông Bắc Á', NULL),
('TSN', 'Tianjin, China  (TSN)', 'Đông Bắc Á', NULL),
('TTN', 'Đài Nam  (TTN)', 'Đông Bắc Á', NULL),
('TYO', 'Tokyo  (TYO)', 'Đông Bắc Á', NULL),
('UIH', 'Quy Nhon  (UIH)', 'Việt Nam', NULL),
('VCA', 'Can Tho (VCA)', 'Việt Nam', 1),
('VCL', 'Chu Lai  (VCL)', 'Việt Nam', NULL),
('VCS', 'Con Dao  (VCS)', 'Việt Nam', 0),
('VDH', 'Dong Hoi  (VDH)', 'Việt Nam', NULL),
('VIE', 'Vienne, Austria  (VIE)', 'Châu Âu', NULL),
('VII', 'Vinh  (VII)', 'Việt Nam', 1),
('VKG', 'Rach Gia  (VKG)', 'Việt Nam', NULL),
('VTE', 'Vientiane  (VTE)', 'Đông Dương', NULL),
('WAS', 'Washington  (WAS)', 'Hoa Kỳ', NULL),
('XDB', 'Lille - Europe, France  (XDB)', 'Châu Âu', NULL),
('XHK', 'Valence RR, France  (XHK)', 'Châu Âu', NULL),
('XIY', 'Xian, China  (XIY)', 'Đông Bắc Á', NULL),
('XIZ', 'Champagne TGV, France  (XIZ)', 'Châu Âu', NULL),
('XOP', 'Poitiers, France  (XOP)', 'Châu Âu', NULL),
('XPJ', 'Montpellier, France  (XPJ)', 'Châu Âu', NULL),
('XRF', 'Marseille St Charles, France  (XRF)', 'Châu Âu', NULL),
('XSH', 'St-Pierre des Corps, France  (XSH)', 'Châu Âu', NULL),
('XWG', 'Strasbourg, France  (XWG)', 'Châu Âu', NULL),
('XYD', 'Lyon Part - Dieu, France  (XYD)', 'Châu Âu', NULL),
('XZN', 'Avignon TGV, France  (XZN)', 'Châu Âu', NULL),
('XZV', 'Toulon, France  (XZV)', 'Châu Âu', NULL),
('YVR', 'Vancouver, Canada  (YVR)', 'Hoa Kỳ', NULL),
('ZFJ', 'Rennes, France  (ZFJ)', 'Châu Âu', NULL),
('ZFQ', 'Bordeaux St Jean, France  (ZFQ)', 'Châu Âu', NULL),
('ZLN', 'Le Mans, France  (ZLN)', 'Châu Âu', NULL),
('ZRH', 'Zurich, Switzerland  (ZRH)', 'Châu Âu', NULL),
('ZYN', 'Nîmes, France  (ZYN)', 'Châu Âu', NULL);

--
-- Dumping data for table `tbtaikhoan`
--

INSERT INTO `tai_khoan` (`id`, `ky_hieu`, `mo_ta`, `loai`, `phan_loai`, `phi_vn`, `phi_vj`, `phi_jets`, `phi_bb`,
 `mst`, `dia_chi`, `email`, `sdt`, `so_du_ky_truoc`, `ngay_tao`, `ghi_chu`) VALUES
(15, 'NỢ VÉ', 'NỢ VÉ', -1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0.0000', NULL, NULL),
(24, 'Dư', 'Dư', -1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0.0000', NULL, NULL),
(50, '1.TM', 'AGRIBANK-THANH', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0.0000', NULL, NULL),
(51, 'AGR', 'AGRIBANK-THANH', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0.0000', NULL, NULL),
(52, 'TCB', 'TECKCOMBANK-THANH', 0, NULL, '0.0000', '0.0000', '0.0000', NULL, NULL, NULL, NULL, NULL, '0.0000', NULL, NULL),
(53, '4. A Minh', 'A Minh', 0, NULL, '0.0000', '0.0000', '0.0000', NULL, NULL, NULL, NULL, NULL, '0.0000', NULL, NULL),
(54, '5. TECK -CT', 'TECKCOMBANK-CT', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0.0000', NULL, NULL),
(55, 'VCB', 'VIETCOMBANK', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0.0000', '2018-06-01', NULL),
(56, '7. VCB-CT', 'VIETCOMBANK-CT', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0.0000', NULL, NULL),
(57, '8. SACOM', 'SACOMBANK', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0.0000', NULL, NULL),
(58, 'BIDV', 'BIDV', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0.0000', NULL, NULL),
(59, '10. VIETIN', 'VIETINBANK-THANH', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0.0000', NULL, NULL),
(60, 'BAO GIA TRAN', 'BẢO GIA TRAN', 1, 'Vé máy bay', '6000.0000', '6000.0000', '6000.0000', '6000.0000', 'mstbao', 'sdtbao', 'mailbao', '', '0.0000', NULL, NULL),
(61, 'NGOC MAI', 'NGỌC MAI', 1, 'Vé máy bay', '8000.0000', '8000.0000', '8000.0000', '8000.0000', NULL, NULL, NULL, '', '0.0000', NULL, NULL),
(62, 'DUNG THANH', 'DŨNG THÀNH', 1, 'Vé máy bay', '0.0000', '0.0000', '0.0000', NULL, NULL, NULL, NULL, '', '0.0000', NULL, NULL),
(63, 'KINH BAC', 'KINH BẮC', 1, 'Vé máy bay', '0.0000', '0.0000', '0.0000', NULL, NULL, NULL, NULL, '', '0.0000', NULL, NULL),
(81, 'HOANG HA', 'Nhà xe Hoàng Hà', 1, 'Nhà xe', '0.0000', '0.0000', '0.0000', NULL, '123244', 'Hà Nội', NULL, '0795834858', '0.0000', NULL, NULL),
(82, 'VUON TRAU', 'Nhà Hàng Vườn trầu', 1, 'Nhà hàng', '0.0000', '0.0000', '0.0000', NULL, NULL, NULL, NULL, '0986376194', '0.0000', NULL, NULL);

--
-- Dumping data for table `tbthuephi`
--

INSERT INTO `thue_phi` (`id`, `loai_phi`, `muc_phi`, `ghi_chu`) VALUES
(1, 'Phí soi chiếu, an ninh nhóm A | VN | Người lớn', '120000.0000', NULL),
(2, 'Phí soi chiếu, an ninh nhóm A | VN | Trẻ em', '60000.0000', NULL),
(3, 'Phí soi chiếu, an ninh nhóm A | VJ | Người lớn', '120000.0000', NULL),
(4, 'Phí soi chiếu, an ninh nhóm A | VJ | Trẻ em', '60000.0000', NULL),
(5, 'Phí soi chiếu, an ninh nhóm A | Jets | Người lớn', '120000.0000', NULL),
(6, 'Phí soi chiếu, an ninh nhóm A | Jets | Trẻ em', '60000.0000', NULL),
(7, 'Phí soi chiếu, an ninh nhóm B | VN | Người lớn', '100000.0000', NULL),
(8, 'Phí soi chiếu, an ninh nhóm B | VN | Trẻ em', '50000.0000', NULL),
(9, 'Phí soi chiếu, an ninh nhóm B | VJ | Người lớn', '100000.0000', NULL),
(10, 'Phí soi chiếu, an ninh nhóm B | VJ | Trẻ em', '50000.0000', NULL),
(11, 'Phí soi chiếu, an ninh nhóm B | Jets | Người lớn', '100000.0000', NULL),
(12, 'Phí soi chiếu, an ninh nhóm B | Jets | Trẻ em', '50000.0000', NULL),
(13, 'Phí quản trị | VN | Chặng dài', '150000.0000', NULL),
(14, 'Phí quản trị | VN | Chặng ngắn', '80000.0000', NULL),
(15, 'Phí quản trị | VJ', '210000.0000', NULL),
(16, 'Phí quản trị | Jets', '210000.0000', NULL),
(17, 'Phí soi chiếu, an ninh nhóm A | BB | Người lớn', '120000.0000', NULL),
(18, 'Phí soi chiếu, an ninh nhóm A | BB | Trẻ em', '60000.0000', NULL),
(19, 'Phí soi chiếu, an ninh nhóm B | BB | Người lớn', '100000.0000', NULL),
(20, 'Phí soi chiếu, an ninh nhóm B | BB | Trẻ em', '50000.0000', NULL),
(21, 'Phí quản trị | BB', '210000.0000', NULL);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
