export const CHANGE_PAGE_TITLE = "CHANGE_PAGE_TITLE";
export const CHANGE_MENU_ACTIVE = "CHANGE_MENU_ACTIVE";

export const LOGOUT = "LOGOUT";
export const SET_AUTH = "SET_AUTH";

///////////////////////////////////////
export const LOADING_SAN_BAY_LIST = "LOADING_SAN_BAY_LIST";
export const SET_SAN_BAY_LIST = "SET_SAN_BAY_LIST";
export const ERROR_SAN_BAY_LIST = "ERROR_SAN_BAY_LIST";

export const LOADING_THUE_PHI_LIST = "LOADING_THUE_PHI_LIST";
export const SET_THUE_PHI_LIST = "SET_THUE_PHI_LIST";
export const ERROR_THUE_PHI_LIST = "ERROR_THUE_PHI_LIST";

export const LOADING_PHI_HANH_LY_LIST = "LOADING_PHI_HANH_LY_LIST";
export const SET_PHI_HANH_LY_LIST = "SET_PHI_HANH_LY_LIST";
export const ERROR_PHI_HANH_LY_LIST = "ERROR_PHI_HANH_LY_LIST";

export const LOADING_TAI_KHOAN_LIST = "LOADING_TAI_KHOAN_LIST";
export const SET_TAI_KHOAN_LIST = "SET_TAI_KHOAN_LIST";
export const ERROR_TAI_KHOAN_LIST = "ERROR_TAI_KHOAN_LIST";

export const LOADING_KHACH_HANG_LIST = "LOADING_KHACH_HANG_LIST";
export const SET_KHACH_HANG_LIST = "SET_KHACH_HANG_LIST";
export const ERROR_KHACH_HANG_LIST = "ERROR_KHACH_HANG_LIST";

export const LOADING_HANG_BAY_LIST = "LOADING_HANG_BAY_LIST";
export const SET_HANG_BAY_LIST = "SET_HANG_BAY_LIST";
export const ERROR_HANG_BAY_LIST = "ERROR_HANG_BAY_LIST";

export const LOADING_HANG_HOA_LIST = "LOADING_HANG_HOA_LIST";
export const SET_HANG_HOA_LIST = "SET_HANG_HOA_LIST";
export const ERROR_HANG_HOA_LIST = "ERROR_HANG_HOA_LIST";
